oldmai=par("mai")
par(mai=c(0,0,0,0))
pdf("~/dev/imc-2016-georouting-paper/kde_comparison.pdf", paper="special", width=16, height=14, pointsize=32)
d_1<-density(global.pse.lm, bw="SJ")
d_2<-density(global.pse.lasso,  bw="SJ")
d_3<-density(rt.pse.avg,  bw="SJ")
d_4<-density(rt.pse.full,  bw="SJ")
plot(d_1, ylim=c(0,0.08), xlim=c(-80, 70), main="",  xaxt="n", xlab="", ylab="")
par(new=TRUE)
plot(d_2, ylim=c(0,0.08), xlim=c(-80, 70), main="",xaxt="n", xlab="", ylab="")
par(new=TRUE)
plot(d_3, ylim=c(0,0.08), xlim=c(-80, 70), main="",xaxt="n", xlab="", ylab="")
par(new=TRUE)
plot(d_4, ylim=c(0,0.08), xlim=c(-80, 70), main="", xlab="", ylab="")
polygon(d_1, col=rgb(1, 0, 0,0.4))
polygon(d_2, col=rgb(0, 1, 1,0.4))
polygon(d_3, col=rgb(1, 1, 0, 0.3))
polygon(d_4, col=rgb(0, 0, 0,0.4))
legend("topleft", ncol=1, c("LR (no regularisation)", "LASSO LR", "Decision Tree (leaf avg)", "Decision Tree (leaf LR)"), fill=c(rgb(1, 0, 0,0.4), rgb(0, 1, 1,0.4), rgb(1, 1, 0,0.3),rgb(0, 0, 0,0.4)), bty="n", cex=1.0, inset=0.00, xjust = 1, yjust = 1)

#title(main="KDE of prediction error")
mtext(text='Prediction Error',side=1,line=2)
mtext(text='Density',side=2,line=2)
dev.off()
